repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-json
        exclude: |
            (?x)^(
                .vscode/.*.json
            )$
    -   id: check-yaml
    -   id: check-toml
    -   id: mixed-line-ending
        args: ["--fix=lf"]
-   repo: local
    hooks:
    -   id: clang-format-llvm
        name: clang-format (LLVM style)
        entry: clang-format
        language: system
        files: \.(c|h|cpp|hpp|cc|cxx)$
        args: ["-i", "--style=LLVM"]
