/*
 * POK build dependencies - auto-generated placeholder
 * This file may be generated by build configuration tools
 */
#ifndef __POK_DEPENDENCIES_H__
#define __POK_DEPENDENCIES_H__

/* Build configuration dependencies */
#define POK_CONFIG_NB_PROCESSORS 1
#define POK_ERROR_MAX_LOGGED 10

/* ARM architecture needs */
#ifdef POK_ARCH_ARM
#define POK_NEEDS_CONSOLE 1
#define POK_NEEDS_DEBUG 1
#endif

#endif /* __POK_DEPENDENCIES_H__ */
