#include "subprograms.h"
#include <assert.h>
#include <core/event.h>
#include <core/lockobj.h>
#include <core/thread.h>
#include <errno.h>
#include <types.h>
#ifdef POK_NEEDS_DEBUG
#include <libc/stdio.h>
#endif
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
/*  Periodic task : thr1*/
extern pok_event_id_t input_id;

volatile int thr1_counter = 0;
volatile int thr2_counter = 0;

void *thr1_job(void) {
  while (1) {
    thr1_counter++;
    /*  Send the OUT ports*/
    pok_event_signal(input_id);
    pok_thread_period();
  }
}

/*  Periodic task : thr2*/
void *thr2_job(void) {
  pok_ret_t ret;
  while (1) {
    thr2_counter++;
    /*  Get the IN ports values*/
    ret = pok_event_wait(input_id, 0);
    if (ret == POK_ERRNO_OK) {
      pok_testevents__spg_receive_event();
    }
    pok_thread_period();
  }
}
