/*
 * POK build dependencies - auto-generated placeholder
 * This file may be generated by build configuration tools
 */
#ifndef __POK_DEPENDENCIES_H__
#define __POK_DEPENDENCIES_H__

/* Build configuration dependencies */
/* This file can be populated by build scripts if needed */

#endif /* __POK_DEPENDENCIES_H__ */
