// This file has been automatically generated by gen_deployment.
// Do not make manual modifications there or they will be lost.

#ifndef __POK_USER_GENERATED_DEPLOYMENT_H_
#define __POK_USER_GENERATED_DEPLOYMENT_H_

#define POK_NEEDS_LIBC_STDLIB 1
#define POK_NEEDS_TIMER 1

#define POK_CONFIG_NB_PROCESSORS 1
#define POK_CONFIG_NB_PARTITIONS 2
#define POK_CONFIG_NB_THREADS 7

#endif // __POK_USER_GENERATED_DEPLOYMENT_H_
